services:
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: admin
      POSTGRES_DB: database
    ports:
      - "5433:5432"
    volumes:
      - ./DB/data:/var/lib/postgresql/data
      - ./DB/scripts:/scripts/
  file_server:
    image: alpine:3.14
    container_name: file_server
    ports:
      - "5215:5215"
    volumes:
      - ./FileServer/zig-out/bin:/file_server
    entrypoint: [/file_server/FileServer]
  API:
    image: alpine:3.14
    container_name: API
    working_dir: /API
    ports:
      - "5010:5010"
    volumes:
      - ./API/logs:/API/logs
      - ./API/target/release:/API
    entrypoint: ["/API/API"]

  APP:
    image: node:20-alpine
    container_name: APP
    working_dir: /APP
    ports: 
      - "5173:5173"
    volumes:
      - ./APP:/APP
    entrypoint: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]


volumes:
  db_data:
    driver: local
